import { Inter } from "next/font/google";
import "@/_styles/globals.css";
import { Header } from "@/components/Header/Header";
import { Masthead } from "@/components/Masthead/Masthead";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Masthead />
        {children}
      </body>
    </html>
  );
}
